---
# Source: promstack/charts/tempo/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promstack-tempo
  namespace: monitoring
  labels:
    helm.sh/chart: tempo-1.18.3
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: promstack
    app.kubernetes.io/version: "2.7.1"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
