{
 "title": "CX / FluxCD",
 "tags": [
  "flux",
  "cx"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "workqueue_work_duration_seconds_count"
    }
   },
   { "name": "interval", "label": "interval", "query": "1m,5m,1h" }
  ]
 },
 "panels": [
  { "title": "Objects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Releases Managed",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "gotk_reconcile_condition{type=\"Ready\",status=\"False\",kind=~\"Kustomization|HelmRelease\"}"
    }
   ]
  },
  {
   "title": "Source acquisition readiness ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "gotk_reconcile_condition{type=\"Ready\",status=\"False\",kind=~\"GitRepository|HelmRepository|Bucket\"}"
    }
   ]
  },
  {
   "title": "Object reconciliation duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "  sum(rate(gotk_reconcile_duration_seconds_sum{kind=~\"Kustomization|HelmRelease\"}[1h])) by (kind, name)\n/\n  sum(rate(gotk_reconcile_duration_seconds_count{kind=~\"Kustomization|HelmRelease\"}[1h])) by (kind, name)",
     "legendFormat": "{{`{{`}} kind {{`}}`}}/{{`{{`}} name {{`}}`}}"
    }
   ]
  },
  {
   "title": "Source reconciliation duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "  sum(rate(gotk_reconcile_duration_seconds_sum{kind=~\"GitRepository|HelmRepository|Bucket\"}[1h])) by (kind, name)\n/\n  sum(rate(gotk_reconcile_duration_seconds_count{kind=~\"GitRepository|HelmRepository|Bucket\"}[1h])) by (kind, name)",
     "legendFormat": "{{`{{`}} kind {{`}}`}}/{{`{{`}} name {{`}}`}}"
    }
   ]
  },
  {
   "title": "Flux Internal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max Work Queue",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(workqueue_longest_running_processor_seconds{namespace=\"$namespace\",pod=~\".*-controller-.*\"})",
       "legendFormat": "seconds"
      }
     ]
    },
    {
     "title": "Suspended Objects",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(gotk_suspend_status{namespace=\"$namespace\",pod=~\".*-controller-.*\"})",
       "legendFormat": "seconds"
      }
     ]
    },
    {
     "title": "Failing Objects",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(gotk_reconcile_condition{exported_namespace=~\"$namespace\",type=\"Ready\",status=\"False\"})"
      }
     ]
    },
    {
     "title": "Total Objects",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(sum(gotk_reconcile_condition{exported_namespace=~\"$namespace\"}) by (kind,name))",
       "legendFormat": "seconds"
      }
     ]
    },
    {
     "title": "API Requests per $interval",
     "type": "stat",
     "gridPos": { "h": 5, "w": 9, "x": 12, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(rest_client_requests_total{namespace=\"$namespace\",pod=~\".*-controller-.*\"}[$interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Optimal Concurrency",
     "type": "stat",
     "description": "A recommended value for the kustomization controller's `--concurrent` flag that would not result in apply delays with the current number of kustomizations and the avg number of time they take.",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(sum(increase(workqueue_work_duration_seconds_sum{name=\"kustomization\"}[1h]))  / sum(increase(workqueue_work_duration_seconds_count{name=\"kustomization\"}[1h]))) * sum(gotk_reconcile_condition{exported_namespace=~\"$namespace\", kind=\"Kustomization\"}) / 60",
       "legendFormat": "seconds"
      }
     ]
    },
    {
     "title": "Kubernetes API Requests per $interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(rest_client_requests_total{namespace=\"$namespace\"}[$interval]))",
       "legendFormat": "total"
      },
      {
       "expr": "sum(increase(rest_client_requests_total{namespace=\"$namespace\",code!~\"2..\"}[$interval]))",
       "legendFormat": "errors"
      }
     ]
    },
    {
     "title": "Cluster Reconciliation Duration",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(workqueue_longest_running_processor_seconds{name=\"kustomization\"}) by (pod)",
       "legendFormat": "{{`{{`}} pod {{`}}`}}"
      }
     ]
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Deployment Compute Usage",
   "type": "table",
   "description": "Click through for deployment level details",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{namespace=\"flux\", deployment=~\".*\"}"
    }
   ]
  },
  {
   "title": "Deployment Network Usage",
   "type": "table",
   "description": "Click through for deployment level details",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{namespace=\"flux\", deployment=~\".*\"}"
    }
   ]
  },
  { "title": "Reconciliation Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Cluster Reconciliations ops/$interval",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{controller=\"kustomization\",result!=\"error\"}[$interval])) by (controller)",
     "legendFormat": "successful reconciliations "
    },
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{controller=\"kustomization\",result=\"error\"}[$interval])) by (controller)",
     "legendFormat": "failed reconciliations "
    }
   ]
  },
  {
   "title": "Git Sources ops/$interval",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{controller=\"gitrepository\",result!=\"error\"}[$interval]))",
     "legendFormat": "successful git pulls"
    },
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{controller=\"gitrepository\",result=\"error\"}[$interval]))",
     "legendFormat": "failed git pulls"
    }
   ]
  },
  { "title": "Controller Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Controller ops/$interval",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{result!=\"error\"}[$interval])) by (controller)",
     "legendFormat": "{{`{{`}}  controller  {{`}}`}} "
    }
   ]
  },
  {
   "title": "Controller errors/$interval",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{result=\"error\"}[$interval])) by (controller)",
     "legendFormat": "{{`{{`}} controller {{`}}`}} "
    }
   ]
  }
 ]
}