---
# Source: promstack/charts/kube-prometheus-stack/charts/grafana/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: promstack-grafana
  namespace: monitoring
  labels:
    helm.sh/chart: grafana-8.10.1
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: promstack
    app.kubernetes.io/version: "11.5.2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: promstack-grafana
subjects:
- kind: ServiceAccount
  name: promstack-grafana
  namespace: monitoring
