{
 "title": "CX / Prometheus",
 "tags": [
  "prometheus",
  "cx"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "interval", "query": "1m,5m,1h" },
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Performance last $interval", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Versions",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(avg(prometheus_build_info) by (repository, container, version), \"repository\", \"$1/$1\", \"container\", \"(.*)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(avg(prometheus_operator_build_info) by (repository, container, version), \"repository\", \"prometheus-operator/prometheus-operator\", \"container\", \"(.*)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(avg(grafana_build_info) by (repository, container, version), \"repository\", \"grafana/grafana\", \"container\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time Series",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(prometheus_tsdb_head_series{container=\"prometheus\"})",
     "legendFormat": "{{pod}} head series"
    }
   ]
  },
  {
   "title": "Intervals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(prometheus_target_interval_length_seconds_sum{}[$interval]) / rate(prometheus_target_interval_length_seconds_count{}[$interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(prometheus_rule_group_interval_seconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(scrape_duration_seconds{job=~\".+\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Evaluation Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(prometheus_rule_group_last_duration_seconds[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runs per $interval",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prometheus_tsdb_head_samples_appended_total[$interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(prometheus_rule_evaluations_total[$interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(prometheus_sd_kubernetes_http_request_total[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Live Counts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_exemplar_exemplars_in_storage{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(count(prometheus_rule_group_rules) by (rule_group))",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(prometheus_sd_discovered_targets)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prometheus_rule_evaluation_failures_total{}[$interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(prometheus_rule_group_iterations_missed_total{}[$interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(scrape_duration_seconds >= 10)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metric Cardinality by Job",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cardinality Breakdown",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(scrape_samples_scraped) by (job)",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "sum(scrape_samples_post_metric_relabeling) by (job)",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "max(time() - process_start_time_seconds{}) by (job) ",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Top Metric Producing Jobs",
   "type": "timeseries",
   "description": "Counts before relabelings",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(scrape_samples_scraped) by (job) > 64",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Top Sampling Rate After Relabelings",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(scrape_samples_post_metric_relabeling) by (job) > 32",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Evaluation Timings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Slowest Rule Group Evaluations per $interval",
   "type": "timeseries",
   "description": "Slowest rule group evaluation times (above > 1s).\nWarnings happen when they take longer than their evaluation period.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, label_replace(\n\nsum(avg_over_time(prometheus_rule_group_last_duration_seconds[$interval])) by (rule_group) > 0.001,\n\n\"rule\", \"$1\", \"rule_group\", \".*yaml;(.*)\" ))",
     "legendFormat": "{{rule}}"
    }
   ]
  },
  {
   "title": "Slowest Rule Group Evaluations Normalised per $interval",
   "type": "timeseries",
   "description": "Percentage of time prometheus spends computing the rule. Basically the previous panel, but divided by the group interval (how frequently it should re-evaluate).\n\nOnly showing ones active more than 0.01% of the time.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(5, label_replace(\nsum(avg_over_time(prometheus_rule_group_last_duration_seconds[$interval]) / avg_over_time(prometheus_rule_group_interval_seconds[$interval])) by (rule_group) > 0.0001,\n\"rule\", \"$1\", \"rule_group\", \".*yaml;(.*)\" ))",
     "legendFormat": "{{rule }}"
    }
   ]
  },
  {
   "title": "Evaluation Failures / Misses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Evaluation Failures",
     "type": "timeseries",
     "description": "Rules where evaluation failures have been noted. If this persists, please go to prometheus rules and look at reasons for why. If they persist it could lead to data loss on recording rules, and alerts not firing.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "label_replace( (sum(increase(prometheus_rule_evaluation_failures_total{namespace=\"monitoring\"}[$interval])) by (rule_group) > 0), \"rule\", \"$1\", \"rule_group\", \".*yaml;(.*)\" )",
       "legendFormat": "{{rule}}"
      }
     ]
    },
    {
     "title": "Missed Evaluations per $interval",
     "type": "timeseries",
     "description": "Rule group evaluations that got missed",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "label_replace(\nsum(increase(prometheus_rule_group_iterations_missed_total{}[$interval])) by (rule_group) >0,\n\"rule\", \"$1\", \"rule_group\", \".*yaml;(.*)\" )",
       "legendFormat": "{{rule}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubernetes Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Kubernetes Statefulsets",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas{namespace=\"monitoring\"}"
    }
   ]
  },
  {
   "title": "Kubernetes Deployments",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{namespace=\"monitoring\", deployment=~\".*(promstack|prometheus-stack|thanos|metrics-server|kube-state).*\"}"
    }
   ]
  },
  { "title": "Scraping", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Scrape Timeouts",
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 38 },
   "options": {
    "content": "- Scrape timeouts (at 10s) trigger [TargetDown](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/general.rules.yaml#L27) alerts\n- Faulty nodes can fail kubelet.  Refresh `ep promstack-kubelet` to force operator updates."
   }
  },
  {
   "title": "Sync Durations",
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 38 },
   "options": {
    "content": "- Sync durations are durations for Kubernetes sync for service discovery\n- Sync durations should only be high for multi-scrape jobs such as mesh + catch-all monitors."
   }
  },
  {
   "title": "Scrape Durations",
   "type": "timeseries",
   "description": "Scrape duration (10s RED is timeout)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(scrape_duration_seconds{job=~\".+\"}) by (job) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Long Sync Durations",
   "type": "timeseries",
   "description": "Jobs with total sync times > 0s across all its targets.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(prometheus_target_sync_length_seconds_sum{}[$interval])) by (scrape_job) ",
     "legendFormat": "{{scrape_job}}"
    }
   ]
  },
  {
   "title": "Query",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg(rate(prometheus_engine_query_duration_seconds_count{slice=\"inner_eval\"}[$interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Query Durations by Stage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max by (slice) (prometheus_engine_query_duration_seconds{quantile=\"0.9\"}) * 1e3",
       "legendFormat": "{{slice}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scrape failures",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_target_scrapes_exceeded_body_size_limit_total{}[1h]))",
       "legendFormat": "exceeded body size limit"
      },
      {
       "expr": "sum(increase(prometheus_target_scrapes_exceeded_sample_limit_total{}[1h]))",
       "legendFormat": "exceeded sample limit"
      },
      {
       "expr": "sum(increase(prometheus_target_scrapes_sample_duplicate_timestamp_total{}[1h]))",
       "legendFormat": "duplicate timestamp"
      },
      {
       "expr": "sum(increase(prometheus_target_scrapes_sample_out_of_bounds_total{}[1h]))",
       "legendFormat": "out of bounds"
      },
      {
       "expr": "sum(increase(prometheus_target_scrapes_sample_out_of_order_total{}[1h]))",
       "legendFormat": "out of order"
      }
     ]
    },
    {
     "title": "Appended Samples",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_tsdb_head_samples_appended_total{}[$interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "User Facing SLIs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Duration P99",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(prometheus_engine_query_duration_seconds{quantile=\"0.99\"})",
       "legendFormat": "prometheus"
      }
     ]
    },
    {
     "title": "Query Availability",
     "type": "timeseries",
     "description": "What percentage of  queries successfully respond without server errors.",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_http_requests_total{code!~\"5..\"}[$interval])) / sum(increase(prometheus_http_requests_total[$interval] ))",
       "legendFormat": "prometheus"
      },
      {
       "expr": "sum(increase(grafana_datasource_request_total{code!~\"5..\"}[$interval])) / sum(increase(grafana_datasource_request_total[$interval]))",
       "legendFormat": "grafana"
      }
     ]
    },
    {
     "title": "Error Rates",
     "type": "timeseries",
     "description": "Metrics that indicate problems when percentages are noticeable.",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(prometheus_rule_evaluation_failures_total{}[$interval])) / sum(rate(prometheus_rule_evaluations_total[$interval]))",
       "legendFormat": "evaluation_failures"
      },
      {
       "expr": "sum(rate(prometheus_rule_group_iterations_missed_total{}[$interval])) / sum(rate(prometheus_rule_evaluations_total[$interval]))",
       "legendFormat": "evaluation_misses"
      }
     ]
    },
    {
     "title": "Pod Availability",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(clamp_max(kube_statefulset_status_replicas_ready{namespace=\"monitoring\", statefulset=~\".*prometheus.*\"}, 1))",
       "legendFormat": "prometheus"
      },
      {
       "expr": "sum(clamp_max(kube_deployment_status_replicas_available{namespace=\"monitoring\", deployment=~\".*grafana\"}, 1))",
       "legendFormat": "grafana"
      }
     ]
    }
   ]
  }
 ]
}