---
# Source: promstack/charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name:  promstack-admission-create
  namespace: monitoring
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: promstack-admission-create
    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: promstack
    app.kubernetes.io/version: "69.8.2"
    app.kubernetes.io/part-of: promstack
    chart: kube-prometheus-stack-69.8.2
    release: "promstack"
    heritage: "Helm"
    app.kubernetes.io/name: promstack-prometheus-operator
    app.kubernetes.io/component: prometheus-operator-webhook
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      name:  promstack-admission-create
      labels:
        app: promstack-admission-create
        
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: promstack
        app.kubernetes.io/version: "69.8.2"
        app.kubernetes.io/part-of: promstack
        chart: kube-prometheus-stack-69.8.2
        release: "promstack"
        heritage: "Helm"
        app.kubernetes.io/name: promstack-prometheus-operator
        app.kubernetes.io/component: prometheus-operator-webhook
    spec:
      containers:
        - name: create
          image: registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.5.1
          imagePullPolicy: IfNotPresent
          args:
            - create
            - --host=promstack-operator,promstack-operator.monitoring.svc
            - --namespace=monitoring
            - --secret-name=promstack-admission
          securityContext:
          
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
          resources:
            {}
      restartPolicy: OnFailure
      serviceAccountName: promstack-admission
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
        seccompProfile:
          type: RuntimeDefault
