---
# Source: promstack/charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name:  promstack-admission
  namespace: monitoring
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: promstack-admission
    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: promstack
    app.kubernetes.io/version: "69.8.2"
    app.kubernetes.io/part-of: promstack
    chart: kube-prometheus-stack-69.8.2
    release: "promstack"
    heritage: "Helm"
    app.kubernetes.io/name: promstack-prometheus-operator
    app.kubernetes.io/component: prometheus-operator-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: promstack-admission
subjects:
  - kind: ServiceAccount
    name: promstack-admission
    namespace: monitoring
