{
 "title": "CX / Alertmanager",
 "tags": [
  "cx",
  "prometheus"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(alertmanager_alerts, namespace)"
   },
   {
    "name": "service",
    "label": "service",
    "query": "label_values(alertmanager_alerts, service)"
   },
   {
    "name": "integration",
    "query": "label_values(alertmanager_notifications_total{integration=~\".*\"}, integration)"
   },
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "interval", "label": "interval", "query": "1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Versions",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(avg(alertmanager_build_info) by (repository, container, version), \"repository\", \"prometheus/alertmanager\", \"container\", \"(.*)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(avg(prometheus_operator_build_info) by (repository, container, version), \"repository\", \"prometheus-operator/prometheus-operator\", \"container\", \"(.*)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(avg(grafana_build_info) by (repository, container, version), \"repository\", \"grafana/grafana\", \"container\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(alertmanager_alerts{namespace=~\"$namespace\",service=~\"$service\", state=\"active\"})",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "max(alertmanager_alerts{namespace=~\"$namespace\",service=~\"$service\", state=\"suppressed\"})",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "max(alertmanager_alerts{namespace=~\"$namespace\",service=~\"$service\", state=\"unprocessed\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Silences",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(alertmanager_silences{namespace=~\"$namespace\",service=~\"$service\", state=\"active\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(alertmanager_silences{namespace=~\"$namespace\",service=~\"$service\", state=\"pending\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(alertmanager_silences{namespace=~\"$namespace\",service=~\"$service\", state=\"expired\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Integrations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(alertmanager_integrations{namespace=~\"$namespace\"})",
     "legendFormat": "{{pod}} head series"
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "stat",
   "description": "Numbers present when running HA alertmanager with alertmanager_cluster metrics present.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(alertmanager_cluster_members{namespace=~\"$namespace\",service=~\"$service\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(alertmanager_cluster_failed_peers{namespace=~\"$namespace\",service=~\"$service\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(alertmanager_cluster_health_score{namespace=~\"$namespace\",service=~\"$service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inhibitions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(alertmanager_inhibition_rules{namespace=~\"$namespace\"})",
     "legendFormat": "{{pod}} head series"
    }
   ]
  },
  {
   "title": "Runs per $interval",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(alertmanager_alerts_received_total{status=\"firing\"}[$interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(alertmanager_alerts_received_total{status=\"resolved\"}[$interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(alertmanager_notifications_total[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Config Load",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(alertmanager_config_last_reload_successful{namespace=~\"$namespace\",service=~\"$service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Send / Receive", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "$integration: Notifications Send Rate per $interval",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(alertmanager_notifications_total{namespace=~\"$namespace\",service=~\"$service\", integration=~\"$integration\"}[$interval])) by (integration)",
     "legendFormat": "{{integration}}"
    },
    {
     "expr": "sum(increase(alertmanager_notifications_failed_total{namespace=~\"$namespace\",service=~\"$service\", integration=~\"$integration\"}[$interval])) by (integration) > 0",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Alerts receive rate per $interval",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(alertmanager_alerts_received_total{namespace=~\"$namespace\",service=~\"$service\"}[$interval])) by (status)",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum(increase(alertmanager_alerts_invalid_total{namespace=~\"$namespace\",service=~\"$service\"}[$interval]))",
     "legendFormat": "invalid"
    }
   ]
  },
  { "title": "Success Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "$integration: Success Rate per $interval",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (\n(sum(increase(alertmanager_notifications_failed_total{namespace=~\"$namespace\",service=~\"$service\", integration=~\"$integration\"}[$interval])) by (integration))\n/\n(sum(increase(alertmanager_notifications_total{namespace=~\"$namespace\",service=~\"$service\", integration=~\"$integration\"}[$interval])) by (integration))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Availability",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(clamp_max(kube_statefulset_status_replicas_ready{namespace=~\"$namespace\", statefulset=~\".*alertmanager.*\"}, 1))",
     "legendFormat": "Alertmanager"
    }
   ]
  },
  {
   "title": "Alert Breakdown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Alerts In Time Frame",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "count(ALERTS{alertstate=\"firing\"}) by (alertname)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Simultaneously Firing",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "sum(ALERTS{alertstate=\"firing\"}) by (alertname) > 1",
       "legendFormat": "{{alertname}}"
      }
     ]
    },
    {
     "title": "Alerts Firing 30d Trend",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count(ALERTS{alertstate=\"firing\"})",
       "legendFormat": "Firing Alerts"
      }
     ]
    }
   ]
  }
 ]
}