{
 "title": "CX / Flux",
 "tags": [
  "flux",
  "cx"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "interval", "label": "interval", "query": "1m,5m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Resource Exceptions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gotk_resource_info{ready=\"False\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(gotk_resource_info{suspended=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Totals Resources",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gotk_resource_info{customresource_kind=\"Kustomization\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(gotk_resource_info{customresource_kind=\"GitRepository\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(gotk_resource_info{customresource_kind=\"OCIRepository\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Evaluation Times",
   "type": "stat",
   "description": "Last Seen Averages over $interval",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(gotk_reconcile_duration_seconds_sum[$interval])) by (kind)\n/\nsum(rate(gotk_reconcile_duration_seconds_count[$interval])) by (kind)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconcile Errors",
   "type": "stat",
   "description": "from controller-runtime in last $interval",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_errors_total{job=~\"flux.*\"}[$interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(controller_runtime_terminal_reconcile_errors_total{job=~\"flux.*\"}[$interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(controller_runtime_reconcile_panics_total{job=~\"flux.*\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconciliation Success% per $interval",
   "type": "stat",
   "description": "As reported by controller-runtime.\nPlotted graph under internal metrics.",
   "gridPos": { "h": 6, "w": 3, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(controller_runtime_reconcile_total{job=~\"flux.*\", result!=\"error\"}[$interval])) by (controller) > 0)\n/\n(sum(increase(controller_runtime_reconcile_total{job=~\"flux.*\"}[$interval])) by (controller))",
     "legendFormat": "{{controller }} "
    }
   ]
  },
  {
   "title": "API Requests per $interval",
   "type": "stat",
   "description": "API server requests seen from Kubernetes POV.\nhttps://kubernetes.io/docs/reference/instrumentation/metrics/",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(rest_client_requests_total{job=~\"flux.*\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Objects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Releases Managed",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "label_replace(gotk_resource_info{customresource_kind=~\"Kustomization|HelmRelease\"}, \"sha\", \"$2\", \"revision\", \"(.*)@sha\\\\d*:(.*)\")"
    }
   ]
  },
  {
   "title": "Sources Tracked",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "label_replace(gotk_resource_info{customresource_kind=~\"GitRepository|HelmRepository|Bucket|OCIRepository\"}, \"sha\", \"$2\", \"revision\", \"(.*)@sha\\\\d*:(.*)\")"
    }
   ]
  },
  {
   "title": "Object reconciliation duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "  sum(rate(gotk_reconcile_duration_seconds_sum{kind=~\"Kustomization|HelmRelease\"}[1h])) by (kind, name)\n/\n  sum(rate(gotk_reconcile_duration_seconds_count{kind=~\"Kustomization|HelmRelease\"}[1h])) by (kind, name)",
     "legendFormat": "{{ kind }}/{{ name }}"
    }
   ]
  },
  {
   "title": "Source reconciliation duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "  sum(rate(gotk_reconcile_duration_seconds_sum{kind=~\"GitRepository|HelmRepository|Bucket|OCIRepository\"}[1h])) by (kind, name)\n/\n  sum(rate(gotk_reconcile_duration_seconds_count{kind=~\"GitRepository|HelmRepository|Bucket|OCIRepository\"}[1h])) by (kind, name)",
     "legendFormat": "{{ kind }}/{{ name }}"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Deployment Compute Usage",
   "type": "table",
   "description": "Click through for deployment level details",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{namespace=~\"flux.*\", deployment=~\".*\"}"
    }
   ]
  },
  {
   "title": "Deployment Network Usage",
   "type": "table",
   "description": "Click through for deployment level details",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{namespace=~\"flux.*\", deployment=~\".*\"}"
    }
   ]
  },
  {
   "title": "Internal Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Reconciliations ops/$interval",
     "type": "timeseries",
     "description": "As reported by controller-runtime",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(controller_runtime_reconcile_total{job=~\"flux.*\", result!=\"error\"}[$interval])) by (controller) > 0",
       "legendFormat": "{{controller }} successes "
      },
      {
       "expr": "sum(increase(controller_runtime_reconcile_total{job=~\"flux.*\", result=\"error\"}[$interval])) by (controller) > 0",
       "legendFormat": "{{ controller }} errors"
      }
     ]
    },
    {
     "title": "Reconciliation Success% per $interval",
     "type": "timeseries",
     "description": "As reported by controller-runtime",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum(increase(controller_runtime_reconcile_total{job=~\"flux.*\", result!=\"error\"}[$interval])) by (controller) > 0)\n/\n(sum(increase(controller_runtime_reconcile_total{job=~\"flux.*\"}[$interval])) by (controller))",
       "legendFormat": "{{controller }} "
      }
     ]
    },
    {
     "title": "Kubernetes API Requests per $interval",
     "type": "timeseries",
     "description": "As seen by kubelet",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(rest_client_requests_total{namespace=~\"flux.*\"}[$interval])) by (pod)",
       "legendFormat": "{{pod }} requests"
      },
      {
       "expr": "sum(increase(rest_client_requests_total{namespace=~\"flux.*\",code!~\"2..\"}[$interval])) by (pod)",
       "legendFormat": "{{ pod }} errors"
      }
     ]
    },
    {
     "title": "Longest Running Processor",
     "type": "timeseries",
     "description": "How many seconds has the longest running processor for workqueue been running.\n\nhttps://kubernetes.io/docs/reference/instrumentation/metrics/",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(workqueue_longest_running_processor_seconds{job=~\"flux.*\"}) by (controller)",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  }
 ]
}