---
# Source: flux/templates/alert.yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flux-alerts
  namespace: monitoring
spec:
  groups:
  - name: FluxSource
    rules:
    - alert: FluxSourceFailing
      annotations:
        description: Flux `{{ $labels.customresource_kind }}` source `{{ $labels.name }}` is failing in `source-controller`.
      for: 10m
      keep_firing_for: 5m
      expr: sum(gotk_resource_info{ready="False", customresource_kind=~"GitRepository|OCIRepository"}) by (name, customresource_kind) >= 1
      labels:
        severity: warning
  - name: FluxApply
    rules:
    - alert: FluxApplyFailing
      annotations:
        description: Flux update for `{{ $labels.name }}` has been failing in `kustomize-controller`.
      for: 5m
      keep_firing_for: 5m
      expr: sum(gotk_resource_info{ready="False", customresource_kind="Kustomization"}) by (name) >= 1
      labels:
        severity: warning
