---
# Source: promstack/charts/kube-prometheus-stack/templates/alertmanager/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: promstack-alertmanager
  namespace: monitoring
  labels:
    app: promstack-alertmanager
    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: promstack
    app.kubernetes.io/version: "69.8.2"
    app.kubernetes.io/part-of: promstack
    chart: kube-prometheus-stack-69.8.2
    release: "promstack"
    heritage: "Helm"
spec:
  
  selector:
    matchLabels:
      app: promstack-alertmanager
      release: "promstack"
      self-monitor: "true"
  namespaceSelector:
    matchNames:
      - "monitoring"
  endpoints:
  - port: http-web
    enableHttp2: true
    path: "/metrics"
    metricRelabelings:
      - action: drop
        regex: ^go_.*
        sourceLabels:
        - __name__
      - action: drop
        regex: ^.*bucket.*
        sourceLabels:
        - __name__
  - port: reloader-web
    path: "/metrics"
    metricRelabelings:
      - action: drop
        regex: ^go_.*
        sourceLabels:
        - __name__
      - action: drop
        regex: ^.*bucket.*
        sourceLabels:
        - __name__
