---
# Source: promstack/charts/kube-prometheus-stack/templates/alertmanager/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: promstack-alertmanager
  namespace: monitoring
  labels:
    app: promstack-alertmanager
    self-monitor: "true"
    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: promstack
    app.kubernetes.io/version: "64.0.0"
    app.kubernetes.io/part-of: promstack
    chart: kube-prometheus-stack-64.0.0
    release: "promstack"
    heritage: "Helm"
spec:
  ports:
  - name: http-web
    port: 9093
    targetPort: 9093
    protocol: TCP
  - name: reloader-web
    appProtocol: http
    port: 8080
    targetPort: reloader-web
  selector:
    app.kubernetes.io/name: alertmanager
    alertmanager: promstack
  sessionAffinity: None
  type: "ClusterIP"
